# cmake/CefSubmodule.cmake
#
# Builds a usable CEF binary-distribution layout (CEF_ROOT) by combining:
#   * cef/  (git submodule)            -> include/, libcef_dll/, cmake/
#   * a downloaded prebuilt archive    -> Release/Chromium Embedded Framework
#                                         .framework (the only macOS artifact
#                                         the cef-project CMake macros need)
#
# This avoids checking in or distributing the multi-hundred-MB binary tarball
# while still letting downstream `find_package(CEF)` work against the staged
# CEF_ROOT under ${CMAKE_BINARY_DIR}/cef-staging/.
#
# Inputs (cache variables):
#   CRONYMAX_CEF_DIST_URL  Full URL to a CEF binary distribution tar.bz2.
#   CRONYMAX_CEF_DIST_SHA256 (optional) Expected SHA-256 of the archive.
#
# Outputs (parent scope):
#   CEF_ROOT                Path to the staged distribution.
#   CEF_SUBMODULE_STAGED    TRUE once setup completes (idempotent guard).

if(CEF_SUBMODULE_STAGED)
  if(EXISTS "${CMAKE_BINARY_DIR}/cef-staging/Release/Chromium Embedded Framework.framework"
     AND EXISTS "${CMAKE_BINARY_DIR}/cef-staging/cmake/FindCEF.cmake")
    return()
  endif()
  # Stage was wiped (e.g. user ran rm -rf build/cef-staging) but the cache
  # still flags us as done. Reset and re-run.
  unset(CEF_SUBMODULE_STAGED CACHE)
  unset(CEF_ROOT CACHE)
endif()

set(_cef_src "${CMAKE_SOURCE_DIR}/cef")
set(_cef_stage "${CMAKE_BINARY_DIR}/cef-staging")

if(NOT EXISTS "${_cef_src}/include/cef_app.h")
  message(FATAL_ERROR
    "cef/ submodule is empty. Run: git submodule update --init")
endif()

# --- Run CEF's translator.py to (re)generate the C-API headers, the
#     cpptoc/ctocpp glue, wrapper_types.h, and libcef_dll_dylib.cc. These
#     files are autogenerated from the C++ headers in include/ and live in
#     the submodule on disk after the run (gitignored upstream). The pure-
#     Python translator only depends on cef/tools/, no Chromium checkout.
set(_translator_stamp "${CMAKE_BINARY_DIR}/cef-translator.stamp")
set(_translator_marker "${_cef_src}/libcef_dll/wrapper_types.h")

# Hash the public headers so we re-run when API surface changes.
file(GLOB_RECURSE _cef_api_headers "${_cef_src}/include/*.h")
string(SHA1 _api_hash "${_cef_api_headers}")
set(_translator_marker_content "${_api_hash}")

set(_run_translator TRUE)
if(EXISTS "${_translator_marker}" AND EXISTS "${_translator_stamp}")
  file(READ "${_translator_stamp}" _existing_hash)
  if(_existing_hash STREQUAL _translator_marker_content)
    set(_run_translator FALSE)
  endif()
endif()

if(_run_translator)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  message(STATUS "Generating CEF wrapper sources via translator.py "
                 "(this can take ~30s on first run)")
  execute_process(
    COMMAND "${Python3_EXECUTABLE}" "${_cef_src}/tools/translator.py"
            --root-dir "${_cef_src}" --force
    OUTPUT_QUIET
    RESULT_VARIABLE _tr_rc
    ERROR_VARIABLE  _tr_err)
  # translator.py exits non-zero at the very end if it can't locate a sibling
  # Chromium checkout to stamp version metadata into cef_paths.gypi. That
  # step is not on our build path -- the wrapper sources are written before
  # it runs -- so we treat the exit status as advisory and only fail if the
  # required output files are missing.
  if(NOT EXISTS "${_translator_marker}")
    message(FATAL_ERROR
      "translator.py did not produce libcef_dll/wrapper_types.h:\n${_tr_err}")
  endif()
  file(WRITE "${_translator_stamp}" "${_translator_marker_content}")
endif()

if(NOT CRONYMAX_CEF_DIST_URL)
  message(FATAL_ERROR
    "CRONYMAX_CEF_DIST_URL is not set. Pick a binary distribution from "
    "https://cef-builds.spotifycdn.com/index.html that matches the cef/ "
    "submodule commit and pass it via -DCRONYMAX_CEF_DIST_URL=...")
endif()

# --- Layout staged CEF_ROOT from submodule sources ---------------------------
file(MAKE_DIRECTORY "${_cef_stage}/cmake")

# Resolve the .in CMake files. Despite the suffix they contain no @VAR@
# placeholders -- CEF's distrib script just renames them. configure_file with
# COPYONLY preserves that behaviour and re-runs only when sources change.
foreach(_name FindCEF cef_macros cef_variables)
  configure_file(
    "${_cef_src}/cmake/${_name}.cmake.in"
    "${_cef_stage}/cmake/${_name}.cmake"
    COPYONLY)
endforeach()

# Source trees from the submodule. include/ is built up by combining the
# binary distribution's headers (authoritative for inlined Chromium tables
# such as cef_net_error_list.h and the GN-generated cef_config.h family)
# with submodule-only headers (the _capi_versions.h family that translator.py
# regenerates locally). The binary headers always win on conflicts.
file(MAKE_DIRECTORY "${_cef_stage}/include")

file(MAKE_DIRECTORY "${_cef_stage}/libcef_dll")
file(GLOB _wrapper_children
  RELATIVE "${_cef_src}/libcef_dll"
  "${_cef_src}/libcef_dll/*")
foreach(_child IN LISTS _wrapper_children)
  if(_child STREQUAL "CMakeLists.txt.in")
    continue()
  endif()
  if(NOT EXISTS "${_cef_stage}/libcef_dll/${_child}")
    file(CREATE_LINK
      "${_cef_src}/libcef_dll/${_child}"
      "${_cef_stage}/libcef_dll/${_child}"
      SYMBOLIC)
  endif()
endforeach()

# libcef_dll/CMakeLists.txt is generated by CEF's translator.py from a
# Mustache-style template. We don't reimplement the translator; instead we
# extract the resolved CMakeLists.txt from the binary distribution below
# (alongside the prebuilt framework). tests/* CMakeLists are skipped since
# we don't compile any of them.

# --- Download prebuilt framework --------------------------------------------
# We only need Release/Chromium Embedded Framework.framework on macOS. The
# upstream archive is the smallest convenient way to get a code-signed,
# version-matched framework, so we fetch the whole thing once and extract just
# what we need.
set(_marker "${_cef_stage}/.cef-bin.stamp")
set(_marker_content "${CRONYMAX_CEF_DIST_URL}")

set(_need_download TRUE)
if(EXISTS "${_marker}")
  file(READ "${_marker}" _existing)
  if(_existing STREQUAL _marker_content
     AND EXISTS "${_cef_stage}/Release/Chromium Embedded Framework.framework")
    set(_need_download FALSE)
  endif()
endif()

if(_need_download)
  # Cache the downloaded archive outside ${CMAKE_BINARY_DIR} so wiping the
  # build directory does not force a 270 MB re-download. Honors
  # CRONYMAX_CEF_CACHE_DIR if the user wants to share the cache across
  # multiple checkouts.
  if(NOT CRONYMAX_CEF_CACHE_DIR)
    set(CRONYMAX_CEF_CACHE_DIR "${CMAKE_SOURCE_DIR}/.cef-cache"
        CACHE PATH "Directory used to cache downloaded CEF binary archives.")
  endif()
  file(MAKE_DIRECTORY "${CRONYMAX_CEF_CACHE_DIR}")
  string(SHA1 _url_hash "${CRONYMAX_CEF_DIST_URL}")
  set(_archive "${CRONYMAX_CEF_CACHE_DIR}/cef-${_url_hash}.tar.bz2")

  message(STATUS "Downloading CEF binary distribution: ${CRONYMAX_CEF_DIST_URL}")
  set(_download_args)
  if(CRONYMAX_CEF_DIST_SHA256)
    list(APPEND _download_args EXPECTED_HASH SHA256=${CRONYMAX_CEF_DIST_SHA256})
  endif()
  if(NOT EXISTS "${_archive}" OR CRONYMAX_CEF_DIST_SHA256)
    file(DOWNLOAD
      "${CRONYMAX_CEF_DIST_URL}"
      "${_archive}"
      SHOW_PROGRESS
      STATUS  _dl_status
      ${_download_args})
    list(GET _dl_status 0 _dl_code)
    if(NOT _dl_code EQUAL 0)
      list(GET _dl_status 1 _dl_msg)
      file(REMOVE "${_archive}")
      message(FATAL_ERROR
        "Failed to download CEF distribution: ${_dl_msg}")
    endif()
  else()
    message(STATUS "  using cached archive: ${_archive}")
  endif()

  set(_extract_dir "${CMAKE_BINARY_DIR}/cef-extract")
  file(REMOVE_RECURSE "${_extract_dir}")
  file(MAKE_DIRECTORY "${_extract_dir}")
  message(STATUS "Extracting CEF framework + headers from binary distribution...")
  # Limit extraction to artifacts not produced by the in-tree submodule:
  #   * Release/Chromium Embedded Framework.framework  -- prebuilt binary
  #   * libcef_dll/CMakeLists.txt                       -- Mustache-templated
  #   * include/                                        -- authoritative for
  #     GN-generated headers (cef_config.h, cef_version.h, ...) and for
  #     headers that get inlined Chromium tables substituted at distrib time
  #     (e.g. base/internal/cef_net_error_list.h).
  file(ARCHIVE_EXTRACT
    INPUT "${_archive}"
    DESTINATION "${_extract_dir}"
    PATTERNS
      "*/Release/Chromium Embedded Framework.framework/*"
      "*/libcef_dll/CMakeLists.txt"
      "*/include/*")

  # The archive's top-level dir is `cef_binary_<version>_<platform>/`; locate
  # it dynamically so we don't have to keep the version string in sync here.
  file(GLOB _top_level "${_extract_dir}/cef_binary_*")
  list(LENGTH _top_level _top_count)
  if(NOT _top_count EQUAL 1)
    message(FATAL_ERROR
      "Unexpected CEF archive layout: expected one cef_binary_* dir, got "
      "${_top_count}")
  endif()
  list(GET _top_level 0 _top)

  set(_src_fw "${_top}/Release/Chromium Embedded Framework.framework")
  if(NOT EXISTS "${_src_fw}")
    message(FATAL_ERROR
      "CEF archive did not contain Release/Chromium Embedded Framework"
      ".framework. Did you point CRONYMAX_CEF_DIST_URL at a macOS build?")
  endif()

  file(REMOVE_RECURSE "${_cef_stage}/Release")
  file(MAKE_DIRECTORY "${_cef_stage}/Release")
  file(RENAME
    "${_src_fw}"
    "${_cef_stage}/Release/Chromium Embedded Framework.framework")

  set(_src_wrapper_cml "${_top}/libcef_dll/CMakeLists.txt")
  if(NOT EXISTS "${_src_wrapper_cml}")
    message(FATAL_ERROR
      "CEF archive did not contain libcef_dll/CMakeLists.txt.")
  endif()
  file(RENAME
    "${_src_wrapper_cml}"
    "${_cef_stage}/libcef_dll/CMakeLists.txt")

  # Move the binary distribution's include/ tree into the staged include/.
  # This is the authoritative source for header content.
  set(_src_inc "${_top}/include")
  if(NOT EXISTS "${_src_inc}/cef_app.h")
    message(FATAL_ERROR "CEF archive did not contain include/cef_app.h.")
  endif()
  file(GLOB_RECURSE _bin_inc_files
    RELATIVE "${_src_inc}"
    "${_src_inc}/*")
  foreach(_h IN LISTS _bin_inc_files)
    get_filename_component(_dir "${_cef_stage}/include/${_h}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dir}")
    file(RENAME "${_src_inc}/${_h}" "${_cef_stage}/include/${_h}")
  endforeach()

  # Layer submodule-only headers on top (notably the include/capi/*_capi_versions.h
  # family that translator.py regenerates locally and that the wrapper sources
  # reference). Symlink in only those that the binary distribution omitted.
  file(GLOB_RECURSE _sub_inc_files
    RELATIVE "${_cef_src}/include"
    "${_cef_src}/include/*.h")
  foreach(_h IN LISTS _sub_inc_files)
    if(NOT EXISTS "${_cef_stage}/include/${_h}")
      get_filename_component(_dir "${_cef_stage}/include/${_h}" DIRECTORY)
      file(MAKE_DIRECTORY "${_dir}")
      file(CREATE_LINK
        "${_cef_src}/include/${_h}"
        "${_cef_stage}/include/${_h}"
        SYMBOLIC)
    endif()
  endforeach()

  file(REMOVE_RECURSE "${_extract_dir}")
  file(WRITE "${_marker}" "${_marker_content}")
  message(STATUS "Staged CEF binary distribution at ${_cef_stage}")
endif()

set(CEF_ROOT "${_cef_stage}" CACHE PATH "Staged CEF binary distribution" FORCE)
set(CEF_SUBMODULE_STAGED TRUE CACHE INTERNAL "")
