# cmake/GenerateIconData.cmake
#
# Invoked as a cmake -P script by CronymaxApp.cmake to generate
# ${CMAKE_BINARY_DIR}/generated/browser/icon_data.cc.
#
# Expected variables (passed via -D):
#   ICONS_DIR   — directory containing *.svg files
#   OUTPUT_FILE — absolute path of the .cc file to write
#
# Each SVG is embedded as a C++ raw string literal (delimiter CRONYMAX_SVG)
# and stored in a static hash map. The delimiter cannot appear in valid SVG/XML.

cmake_minimum_required(VERSION 3.21)

file(GLOB svg_files "${ICONS_DIR}/*.svg")
list(SORT svg_files)

set(out
"// Generated by cmake/GenerateIconData.cmake — do not edit.\n\
#include \"browser/icon_data.h\"\n\
#include <string_view>\n\
#include <unordered_map>\n\
\n\
namespace cronymax {\n\
namespace {\n\
\n\
const std::unordered_map<std::string_view, std::string_view>& IconsMap() {\n\
  static const std::unordered_map<std::string_view, std::string_view> kMap = {\n"
)

foreach(svg_file ${svg_files})
  get_filename_component(name "${svg_file}" NAME)
  file(READ "${svg_file}" svg_content)
  string(APPEND out "    {\"${name}\", R\"CRONYMAX_SVG(${svg_content})CRONYMAX_SVG\"},\n")
endforeach()

string(APPEND out
"  };\n\
  return kMap;\n\
}\n\
\n\
}  // namespace\n\
\n\
std::string_view GetIconSvgData(std::string_view filename) {\n\
  const auto& m = IconsMap();\n\
  const auto it = m.find(filename);\n\
  return it != m.end() ? it->second : std::string_view{};\n\
}\n\
\n\
}  // namespace cronymax\n"
)

get_filename_component(out_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")
file(WRITE "${OUTPUT_FILE}" "${out}")
